platform :ios, '9.0'
target 'Anyone' do
	rn_path = '../node_modules/react-native'
	rn_maps_path = '../node_modules/react-native-maps'
	pod 'GoogleSignIn', '~> 4.4.0'
	pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
	pod 'React', path: rn_path, subspecs: [
		'Core',
		'RCTActionSheet',
		'RCTAnimation',
		'RCTGeolocation',
		'RCTImage',
		'RCTLinkingIOS',
		'RCTNetwork',
		'RCTSettings',
		'RCTText',
		'RCTVibration',
		'RCTWebSocket',
	]

	pod 'react-native-maps', path: rn_maps_path
	pod 'Firebase/Core', '6.3.0'
	pod 'Firebase/Messaging', '6.3.0'
	pod 'Firebase/Database', '6.3.0'
	pod 'Firebase/Auth', '6.3.0'
	pod 'Firebase/Storage', '6.3.0'

	pod 'GoogleMaps'
	pod 'react-native-google-maps', path: rn_maps_path  
	pod 'Fabric', '1.9.0'
	pod 'Crashlytics', '~> 3.12.0'
  pod 'react-native-geocoder', :path => '../node_modules/react-native-geocoder'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'


  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
 pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBAudienceNetwork'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  pod 'Google-Mobile-Ads-SDK'



  pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'


  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
  `rm -rf Pods/leveldb-library/port/win`
end
