# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

 lane :certs do
    match(type: 'development', readonly: true)
  end
 
 lane :force_certs do
    match(type: 'development',force_for_new_devices: true)
 end

  lane :beta do
     build_app(
	scheme: "Anyone",
	workspace: "Anyone.xcworkspace",
	export_method: "development"
     )
      crashlytics(api_token: "02b81ce5d7bf283724b7770acab0ff9fbf69990e",
                build_secret: "a7b73c4c3ae1f288f81d101b26bb014cdd224a67eff5e331e3babd33c6bd7a85")
 
    end
end
