name: Deploy android to Google Play
on:
  push:
    branches:
      - master
    tags: [v*]
jobs:
  install-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn
      # - name: Run tests
      #   run: |
      #     npm test
      - name: Setup env
        env:
          GOOGLE_IOS_ID: ${{ secrets.GOOGLE_IOS_ID }}
          GOOGLE_WEB_ID: ${{ secrets.GOOGLE_IOS_ID }}
          GOOGLE_API_KEY_ANDROID: ${{ secrets.GOOGLE_API_KEY_ANDROID }}
          GOOGLE_API_KEY_IOS: ${{ secrets.GOOGLE_API_KEY_IOS }}
          MYAPP_RELEASE_STORE_FILE: ${{ secrets.MYAPP_RELEASE_STORE_FILIE }}
          MYAPP_RELEASE_KEY_ALIAS: ${{ secrets.MYAPP_RELEASE_KEY_ALIAS }}
          MYAPP_RELEASE_STORE_PASSWORD: ${{ secrets.MYAPP_RELEASE_STORE_PASSWORD }}
          MYAPP_RELEASE_KEY_PASSWORD: ${{ secrets.MYAPP_RELEASE_KEY_PASSWORD }}
        run: |
          ./scripts/setupEnv.sh
      - name: Running build command
        run: |
          cd android
          ./gradlew bundleRelease
      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            android/app/build/outputs/bundle/release/app-release.aab
            android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload bundle to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
          packageName: com.activepals
          releaseFile: android/app/build/outputs/bundle/release/app.aab
          track: alpha
          #userFraction: 0.33
          whatsNewDirectory: whatsnew
          #mappingFile: /app/build/outputs/mapping/release/mapping.txt
