name: Deploy android to Google Play
on:
  push:
    branches:
      - master
jobs:
  install-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn
      # - name: Run tests
      #   run: |
      #     npm test
      - name: Build android aab
        run: |
          touch .env
          echo "GOOGLE_IOS_ID=${{ secrets.GOOGLE_IOS_ID }}" >> .env
          echo "GOOGLE_WEB_ID=${{ secrets.GOOGLE_WEB_ID }}" >> .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
          cd scripts && ENV=production ./envscript.sh
          cd .. && cd android
          echo "MYAPP_RELEASE_KEY_ALIAS=${{ secrets.MYAPP_RELEASE_KEY_ALIAS }}" >> gradle.properties
          echo "MYAPP_RELEASE_STORE_FILE=${{ secrets.MYAPP_RELEASE_STORE_FILE }}" >> gradle.properties
          echo "MYAPP_RELEASE_STORE_PASSWORD=${{ secrets.MYAPP_RELEASE_STORE_PASSWORD }}" >> gradle.properties
          echo "MYAPP_RELEASE_KEY_PASSWORD=${{ secrets.MYAPP_RELEASE_KEY_PASSWORD }}" >> gradle.properties
          ./gradlew bundleRelease
      - name: upload bundle to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
          packageName: com.activepals
          releaseFile: android/app/build/outputs/bundle/release/app.aab
          track: alpha
          #userFraction: 0.33
          whatsNewDirectory: whatsnew
          #mappingFile: /app/build/outputs/mapping/release/mapping.txt