name: Deploy android to Google Play
on:
  push:
    branches:
      - master
    tags: [v*]
jobs:
  install-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn
      # - name: Run tests
      #   run: |
      #     npm test
      - name: Setup env
        run: |
          ./scripts/setupEnv.sh
      - name: Runing build command
        # Run your own gradle command to generate build.
        run: |
          cd android
          ./gradlew bundleRelease
      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            android/app/build/outputs/bundle/release/app-release.aab
            android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload bundle to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
          packageName: com.activepals
          releaseFile: android/app/build/outputs/bundle/release/app.aab
          track: alpha
          #userFraction: 0.33
          whatsNewDirectory: whatsnew
          #mappingFile: /app/build/outputs/mapping/release/mapping.txt
